#Requires AutoHotkey v2.0

; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰
; ZONE CONFIGURATION FILE
; ----------------------------------------------------------------------------------------
; This file is used to map all games zone number to zone names.
; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰


; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰
; ZONE PROPERTIES
; ▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰

global Zone := Map()  ; Initialize a Map object to hold zone ids and names.
Zone.Default := "?"  ; Set a default zone name value to "?".


; World 1: Spawn World
; ----------------------------------------------------------------------------------------
Zone[1] := "Spawn"
Zone[2] := "Colorful Forest"
Zone[3] := "Castle"
Zone[4] := "Green Forest"
Zone[5] := "Autumn"
Zone[6] := "Cherry Blossom"
Zone[7] := "Farm"
Zone[8] := "Backyard"
Zone[9] := "Misty Falls"
Zone[10] := "Mine"
Zone[11] := "Chrystal Caverns"
Zone[12] := "Dead Forest"
Zone[13] := "Dark Forest"
Zone[14] := "Mushroom Field"
Zone[15] := "Enchanted Forest"
Zone[16] := "Crimson Forest"
Zone[17] := "Jungle"
Zone[18] := "Jungle Temple"
Zone[19] := "Oasis"
Zone[20] := "Beach"
Zone[21] := "Coral Reef"
Zone[22] := "Shipwreck"
Zone[23] := "Atlantis"
Zone[24] := "Palm Beach"
Zone[25] := "Tiki"
Zone[26] := "Pirate Cove"
Zone[27] := "Pirate Tavern"
Zone[28] := "Shanty Town"
Zone[29] := "Desert Village"
Zone[30] := "Fossil Digsite"
Zone[31] := "Desert Pyramids"
Zone[32] := "Red Desert"
Zone[33] := "Wild West"
Zone[34] := "Grand Canyons"
Zone[35] := "Safari"
Zone[36] := "Mountains"
Zone[37] := "Snow Village"
Zone[38] := "Icy Peaks"
Zone[39] := "Ice Rink"
Zone[40] := "Ski Town"
Zone[41] := "Hot Springs"
Zone[42] := "Fire and Ice"
Zone[43] := "Volcano"
Zone[44] := "Obsidian Cave"
Zone[45] := "Lava Forest"
Zone[46] := "Underworld"
Zone[47] := "Underworld Bridge"
Zone[48] := "Underworld Castle"
Zone[49] := "Metal Dojo"
Zone[50] := "Fire Dojo"
Zone[51] := "Samurai Village"
Zone[52] := "Bamboo Forest"
Zone[53] := "Zen Garden"
Zone[54] := "Flower Field"
Zone[55] := "Fairytale Meadows"
Zone[56] := "Fairytale Castle"
Zone[57] := "Royal Kingdom"
Zone[58] := "Fairy Castle"
Zone[59] := "Cozy Village"
Zone[60] := "Rainbow River"
Zone[61] := "Colorful Mines"
Zone[62] := "Colorful Mountains"
Zone[63] := "Frost Mountains"
Zone[64] := "Ice Sculptures"
Zone[65] := "Snowman Town"
Zone[66] := "Ice Castle"
Zone[67] := "Polar Express"
Zone[68] := "Firefly Cold Forest"
Zone[69] := "Golden Road"
Zone[70] := "No Path Forest"
Zone[71] := "Ancient Ruins"
Zone[72] := "Runic Altar"
Zone[73] := "Wizard Tower"
Zone[74] := "Witch Marsh"
Zone[75] := "Haunted Forest"
Zone[76] := "Haunted Graveyard"
Zone[77] := "Haunted Mansion"
Zone[78] := "Dungeon Entrance"
Zone[79] := "Dungeon"
Zone[80] := "Treasure Dungeon"
Zone[81] := "Empyrean Dungeon"
Zone[82] := "Mythic Dungeon"
Zone[83] := "Cotton Candy Forest"
Zone[84] := "Gummy Forest"
Zone[85] := "Chocolate Waterfall"
Zone[86] := "Sweets"
Zone[87] := "Toys and Blocks"
Zone[88] := "Carnival"
Zone[89] := "Theme Park"
Zone[90] := "Clouds"
Zone[91] := "Cloud Garden"
Zone[92] := "Cloud Forest"
Zone[93] := "Cloud Houses"
Zone[94] := "Cloud Palace"
Zone[95] := "Heaven Gates"
Zone[96] := "Heaven"
Zone[97] := "Heaven Gate Castle"
Zone[98] := "Colorful Clouds"
Zone[99] := "Rainbow Road"

; World 2: Tech World
; ----------------------------------------------------------------------------------------
Zone[100] := "Tech Spawn"
Zone[101] := "Futuristic City"
Zone[102] := "Hologram Forest"
Zone[103] := "Robot Farm"
Zone[104] := "Bit Stream"
Zone[105] := "Neon Mine"
Zone[106] := "Mushroom Lab"
Zone[107] := "Virtual Garden"
Zone[108] := "Data Tree Farm"
Zone[109] := "Tech Jungle"
Zone[110] := "Lava Jungle"
Zone[111] := "Oasis Ruins"
Zone[112] := "Future Beach"
Zone[113] := "Tech Reef"
Zone[114] := "Robo Pirates"
Zone[115] := "Cyber Cove"
Zone[116] := "Ruinic Desert"
Zone[117] := "Charged Pyramids"
Zone[118] := "Fallout Desert"
Zone[119] := "Tech Wild West"
Zone[120] := "Cuboid Canyon"
Zone[121] := "Frozen Mountains"
Zone[122] := "Frostbyte Forest"
Zone[123] := "Forcefield Mine"
Zone[124] := "Cyber Base Camp"
Zone[126] := "Cracked Iceberg"
Zone[127] := "Melted River"
Zone[128] := "Nexus"
Zone[129] := "Secure Coast"
Zone[130] := "Nuclear Forest"
Zone[131] := "Radiation Mine"
Zone[132] := "Exploded Reactor"
Zone[133] := "Spaceship Dock"
Zone[134] := "Rocket Planet"
Zone[135] := "Lunar Planet"
Zone[136] := "Mars Planet"
Zone[137] := "Saturn Planet"
Zone[138] := "Comet Planet"
Zone[139] := "Galaxy Port"
Zone[140] := "Electric Garden"
Zone[141] := "Mutated Forest"
Zone[142] := "Neon City"
Zone[143] := "Arcade Town"
Zone[144] := "Robot Factory"
Zone[145] := "Egg Incubator"
Zone[146] := "Hi-Tech Hive"
Zone[147] := "Spore Garden"
Zone[148] := "UFO Forest"
Zone[149] := "Alien Lab"
Zone[150] := "Alien Mothership"
Zone[151] := "Space Forge"
Zone[152] := "Space Factory"
Zone[153] := "Space Junkyard"
Zone[154] := "Steampunk Alley"
Zone[155] := "Steampunk Town"
Zone[156] := "Steampunk Clockwork"
Zone[157] := "Steampunk Airship"
Zone[158] := "Circuit Board"
Zone[159] := "Mothership Circuit Board"
Zone[160] := "Wizard Ruins"
Zone[161] := "Wizard Forest"
Zone[162] := "Wizard Tech Forest"
Zone[163] := "Wizard Tech Tower"
Zone[164] := "Wizard Dungeon"
Zone[165] := "Cyberpunk Undercity"
Zone[166] := "Cyberpunk Industrial"
Zone[167] := "Cyberpunk City"
Zone[168] := "Cyberpunk Road"
Zone[169] := "Tech Ninja Kyoto"
Zone[170] := "Tech Samurai"
Zone[171] := "Tech Ninja Village"
Zone[172] := "Tech Ninja City"
Zone[173] := "Dominus Dungeon"
Zone[174] := "Dominus Vault"
Zone[175] := "Dominus Lair"
Zone[176] := "Holographic Powerplant"
Zone[177] := "Holographic City"
Zone[178] := "Holographic Forest"
Zone[179] := "Holographic Mine"
Zone[180] := "Dark Tech Cove"
Zone[181] := "Dark Tech Ruins"
Zone[182] := "Dark Tech Castle"
Zone[183] := "Dark Tech Dungeon"
Zone[184] := "Dark Tech Forest"
Zone[185] := "Hacker Powerplant"
Zone[186] := "Hacker Compound"
Zone[187] := "Hacker Base"
Zone[188] := "Hacker Error"
Zone[189] := "Glitch Forest"
Zone[190] := "Glitch City"
Zone[191] := "Glitch Skyscrapers"
Zone[192] := "Glitch Town"
Zone[193] := "Glitch Quantum"
Zone[194] := "Quantum Forest"
Zone[195] := "Quantum Space Base"
Zone[196] := "Quantum Galaxy"
Zone[197] := "Void Atomic"
Zone[198] := "Void Fracture"
Zone[199] := "Void Spiral"

; World 3: Void World
; ----------------------------------------------------------------------------------------
Zone[200] := "Prison Tower"
Zone[201] := "Prison Block"
Zone[202] := "Prison Cafeteria"
Zone[203] := "Prison Yard"
Zone[204] := "Prison HQ"